{
  "generated_at": "2026-06-03T11:00:00",
  "total_records": 47,
  "county_summary": {
    "Knox": {"count": 8, "cities": ["Knoxville", "Farragut", "Powell", "Corryton"]},
    "Davidson": {"count": 12, "cities": ["Nashville", "Antioch", "Hermitage", "Madison"]},
    "Shelby": {"count": 11, "cities": ["Memphis", "Bartlett", "Germantown", "Millington"]},
    "Hamilton": {"count": 6, "cities": ["Chattanooga", "Hixson", "East Ridge"]},
    "Rutherford": {"count": 5, "cities": ["Murfreesboro", "Smyrna", "La Vergne"]},
    "Montgomery": {"count": 5, "cities": ["Clarksville"]}
  },
  "city_summary": {
    "Nashville": {"count": 7, "county": "Davidson"},
    "Memphis": {"count": 6, "county": "Shelby"},
    "Knoxville": {"count": 5, "county": "Knox"},
    "Chattanooga": {"count": 4, "county": "Hamilton"},
    "Murfreesboro": {"count": 3, "county": "Rutherford"},
    "Clarksville": {"count": 5, "county": "Montgomery"},
    "Antioch": {"count": 3, "county": "Davidson"},
    "Bartlett": {"count": 2, "county": "Shelby"},
    "Hermitage": {"count": 2, "county": "Davidson"},
    "Farragut": {"count": 2, "county": "Knox"}
  },
  "auction_calendar": {
    "June 16, 2026": 14,
    "June 23, 2026": 11,
    "June 30, 2026": 9,
    "July 7, 2026": 8,
    "July 14, 2026": 5
  },
  "equity_breakdown": {
    "HIGH_EQUITY": 12,
    "MODERATE_EQUITY": 15,
    "LOW_EQUITY": 8,
    "UNDERWATER": 5,
    "no_data": 7
  },
  "records": [
    {"county":"Davidson","owner":"Marcus T. Williams","property_address":"4217 Nolensville Pike","property_city":"Nashville","property_state":"TN","property_zip":"37211","auction_date":"June 16, 2026","auction_time":"10:00 AM","auction_location":"Davidson County Courthouse","original_loan_amount":"187500","beneficiary":"First Bank of Tennessee","trustee":"Wilson & Associates LLC","parcel_id":"103-14-0072","scraped_date":"2026-06-03","estimated_value":285000,"equity_estimate":97500,"equity_pct":34.2,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Knox","owner":"Patricia J. Holston","property_address":"2841 Sutherland Ave","property_city":"Knoxville","property_state":"TN","property_zip":"37919","auction_date":"June 16, 2026","auction_time":"10:00 AM","auction_location":"Knox County Courthouse","original_loan_amount":"142000","beneficiary":"Tennessee Valley Federal Credit Union","trustee":"Rubin Lublin LLC","parcel_id":"107-A-020","scraped_date":"2026-06-03","estimated_value":248000,"equity_estimate":106000,"equity_pct":42.7,"equity_flag":"HIGH_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Shelby","owner":"Robert & Linda Okafor","property_address":"1582 Winchester Rd","property_city":"Memphis","property_state":"TN","property_zip":"38116","auction_date":"June 23, 2026","auction_time":"2:00 PM","auction_location":"Shelby County Courthouse","original_loan_amount":"98000","beneficiary":"Wells Fargo Bank NA","trustee":"Shapiro & Kirsch LLP","parcel_id":"075-162-00004","scraped_date":"2026-06-03","estimated_value":115000,"equity_estimate":17000,"equity_pct":14.8,"equity_flag":"LOW_EQUITY","equity_source":"Zillow Estimate"},
    {"county":"Hamilton","owner":"James E. Crabtree","property_address":"5903 Brainerd Rd","property_city":"Chattanooga","property_state":"TN","property_zip":"37411","auction_date":"June 16, 2026","auction_time":"11:00 AM","auction_location":"Hamilton County Courthouse","original_loan_amount":"231000","beneficiary":"Mortgage Solutions Inc","trustee":"Lerner Sampson & Rothfuss","parcel_id":"148F-B-009","scraped_date":"2026-06-03","estimated_value":195000,"equity_estimate":-36000,"equity_pct":-18.5,"equity_flag":"UNDERWATER","equity_source":"Zillow Estimate"},
    {"county":"Davidson","owner":"Sandra K. Beaumont","property_address":"312 Oakwood Ave","property_city":"Nashville","property_state":"TN","property_zip":"37207","auction_date":"June 23, 2026","auction_time":"10:00 AM","auction_location":"Davidson County Courthouse","original_loan_amount":"165000","beneficiary":"Regions Bank","trustee":"Wilson & Associates LLC","parcel_id":"081-14-0224","scraped_date":"2026-06-03","estimated_value":320000,"equity_estimate":155000,"equity_pct":48.4,"equity_flag":"HIGH_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Rutherford","owner":"Derek L. Patel","property_address":"718 NW Broad St","property_city":"Murfreesboro","property_state":"TN","property_zip":"37129","auction_date":"June 30, 2026","auction_time":"10:00 AM","auction_location":"Rutherford County Courthouse","original_loan_amount":"178500","beneficiary":"Freedom Mortgage Corp","trustee":"Brock & Scott PLLC","parcel_id":"022C-B-014.00","scraped_date":"2026-06-03","estimated_value":267000,"equity_estimate":88500,"equity_pct":33.1,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Montgomery","owner":"Anthony & Renee Dukes","property_address":"2204 Peachers Mill Rd","property_city":"Clarksville","property_state":"TN","property_zip":"37042","auction_date":"June 16, 2026","auction_time":"10:00 AM","auction_location":"Montgomery County Courthouse","original_loan_amount":"205000","beneficiary":"Navy Federal Credit Union","trustee":"Rubin Lublin LLC","parcel_id":"042A-E-008","scraped_date":"2026-06-03","estimated_value":238000,"equity_estimate":33000,"equity_pct":13.9,"equity_flag":"LOW_EQUITY","equity_source":"Zillow Estimate"},
    {"county":"Shelby","owner":"Carolyn M. Jefferson","property_address":"3849 Covington Pike","property_city":"Memphis","property_state":"TN","property_zip":"38128","auction_date":"June 23, 2026","auction_time":"1:00 PM","auction_location":"Shelby County Courthouse","original_loan_amount":"88000","beneficiary":"Mid-South Federal CU","trustee":"Shapiro & Kirsch LLP","parcel_id":"087-052-00071","scraped_date":"2026-06-03","estimated_value":142000,"equity_estimate":54000,"equity_pct":38.0,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Knox","owner":"William H. Sexton Jr","property_address":"4412 Holston Dr","property_city":"Knoxville","property_state":"TN","property_zip":"37914","auction_date":"June 30, 2026","auction_time":"10:00 AM","auction_location":"Knox County Courthouse","original_loan_amount":"119000","beneficiary":"Tennessee Commerce Bank","trustee":"Wilson & Associates LLC","parcel_id":"073-A-018","scraped_date":"2026-06-03","estimated_value":198000,"equity_estimate":79000,"equity_pct":39.9,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Davidson","owner":"Lisa M. Thornburg","property_address":"6118 Edmondson Pike","property_city":"Nashville","property_state":"TN","property_zip":"37211","auction_date":"July 7, 2026","auction_time":"10:00 AM","auction_location":"Davidson County Courthouse","original_loan_amount":"312000","beneficiary":"Bank of America NA","trustee":"McCalla Raymer Leibert Pierce","parcel_id":"162-04-0117","scraped_date":"2026-06-03","estimated_value":410000,"equity_estimate":98000,"equity_pct":23.9,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Shelby","owner":"Tommy R. Washington","property_address":"2761 Lamar Ave","property_city":"Memphis","property_state":"TN","property_zip":"38114","auction_date":"June 23, 2026","auction_time":"2:30 PM","auction_location":"Shelby County Courthouse","original_loan_amount":"72500","beneficiary":"Pyramid Federal CU","trustee":"Shapiro & Kirsch LLP","parcel_id":"025-166-00019","scraped_date":"2026-06-03","estimated_value":68000,"equity_estimate":-4500,"equity_pct":-6.6,"equity_flag":"UNDERWATER","equity_source":"Zillow Estimate"},
    {"county":"Hamilton","owner":"Kimberly A. Watts","property_address":"7401 Lee Hwy","property_city":"Chattanooga","property_state":"TN","property_zip":"37421","auction_date":"June 30, 2026","auction_time":"10:00 AM","auction_location":"Hamilton County Courthouse","original_loan_amount":"194000","beneficiary":"Chattanooga Federal CU","trustee":"Lerner Sampson & Rothfuss","parcel_id":"167D-C-010","scraped_date":"2026-06-03","estimated_value":310000,"equity_estimate":116000,"equity_pct":37.4,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Knox","owner":"Frank & Doris Abernathy","property_address":"1009 Merchant Dr","property_city":"Knoxville","property_state":"TN","property_zip":"37912","auction_date":"June 16, 2026","auction_time":"11:00 AM","auction_location":"Knox County Courthouse","original_loan_amount":"235000","beneficiary":"Home Federal Savings Bank","trustee":"Rubin Lublin LLC","parcel_id":"080-085","scraped_date":"2026-06-03","estimated_value":425000,"equity_estimate":190000,"equity_pct":44.7,"equity_flag":"HIGH_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Rutherford","owner":"James T. Ingram","property_address":"3204 Fortress Blvd","property_city":"Murfreesboro","property_state":"TN","property_zip":"37128","auction_date":"June 16, 2026","auction_time":"10:30 AM","auction_location":"Rutherford County Courthouse","original_loan_amount":"289000","beneficiary":"PNC Bank NA","trustee":"Brock & Scott PLLC","parcel_id":"105H-C-006.00","scraped_date":"2026-06-03","estimated_value":null,"equity_estimate":null,"equity_pct":null,"equity_flag":"no_data","equity_source":null},
    {"county":"Davidson","owner":"George P. Lattimore","property_address":"1835 Whites Creek Pike","property_city":"Nashville","property_state":"TN","property_zip":"37207","auction_date":"June 23, 2026","auction_time":"10:00 AM","auction_location":"Davidson County Courthouse","original_loan_amount":"145000","beneficiary":"SunTrust Mortgage Inc","trustee":"Wilson & Associates LLC","parcel_id":"050-09-0031","scraped_date":"2026-06-03","estimated_value":220000,"equity_estimate":75000,"equity_pct":34.1,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Shelby","owner":"Vanessa D. Simmons","property_address":"4502 Raleigh Millington Rd","property_city":"Millington","property_state":"TN","property_zip":"38053","auction_date":"July 7, 2026","auction_time":"1:00 PM","auction_location":"Shelby County Courthouse","original_loan_amount":"126000","beneficiary":"First Tennessee Bank","trustee":"Shapiro & Kirsch LLP","parcel_id":"N0042-A-B00065","scraped_date":"2026-06-03","estimated_value":185000,"equity_estimate":59000,"equity_pct":31.9,"equity_flag":"MODERATE_EQUITY","equity_source":"Zillow Estimate"},
    {"county":"Montgomery","owner":"Richard A. Flynn","property_address":"1106 Kraft St","property_city":"Clarksville","property_state":"TN","property_zip":"37040","auction_date":"June 30, 2026","auction_time":"10:00 AM","auction_location":"Montgomery County Courthouse","original_loan_amount":"158000","beneficiary":"Movement Mortgage LLC","trustee":"McCalla Raymer Leibert Pierce","parcel_id":"073D-A-043","scraped_date":"2026-06-03","estimated_value":241000,"equity_estimate":83000,"equity_pct":34.4,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Hamilton","owner":"Phillip & Gwen Norris","property_address":"2215 Glass St","property_city":"Chattanooga","property_state":"TN","property_zip":"37406","auction_date":"June 16, 2026","auction_time":"11:30 AM","auction_location":"Hamilton County Courthouse","original_loan_amount":"64000","beneficiary":"LoanCare LLC","trustee":"Lerner Sampson & Rothfuss","parcel_id":"136D-B-018","scraped_date":"2026-06-03","estimated_value":128000,"equity_estimate":64000,"equity_pct":50.0,"equity_flag":"HIGH_EQUITY","equity_source":"TN State Assessment"},
    {"county":"Knox","owner":"Brenda R. Coker","property_address":"7219 Ball Camp Pike","property_city":"Knoxville","property_state":"TN","property_zip":"37931","auction_date":"July 14, 2026","auction_time":"10:00 AM","auction_location":"Knox County Courthouse","original_loan_amount":"278000","beneficiary":"Citibank NA","trustee":"Wilson & Associates LLC","parcel_id":"015-152","scraped_date":"2026-06-03","estimated_value":null,"equity_estimate":null,"equity_pct":null,"equity_flag":"no_data","equity_source":null},
    {"county":"Davidson","owner":"Annette C. Boyd","property_address":"2909 Clarksville Pike","property_city":"Nashville","property_state":"TN","property_zip":"37218","auction_date":"June 16, 2026","auction_time":"10:00 AM","auction_location":"Davidson County Courthouse","original_loan_amount":"178000","beneficiary":"JP Morgan Chase Bank","trustee":"Wilson & Associates LLC","parcel_id":"047-08-0111","scraped_date":"2026-06-03","estimated_value":295000,"equity_estimate":117000,"equity_pct":39.7,"equity_flag":"MODERATE_EQUITY","equity_source":"TN State Assessment"}
  ]
}
